name: Build and test

on:
  push:
    branches: [ "dev", "main" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
  workflow_dispatch:

jobs:
  build_apk:
    strategy:
      matrix:
        build_type: ['debug', 'release']
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Assemble ${{ matrix.build_type }} APK
        run: |
          build_type=${{ matrix.build_type }}
          ./gradlew :core:app:assemble${build_type^}
      - name: Copy ${{ matrix.build_type }} APK
        run: |
          cp core/app/build/outputs/apk/${{ matrix.build_type }}/app-*.apk ./
      - name: Upload arm64-v8a ${{ matrix.build_type }} APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-arm64-v8a-${{ matrix.build_type }}
          path: app-arm64-v8a-${{ matrix.build_type }}.apk
      - name: Upload armeabi-v7a ${{ matrix.build_type }} APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-armeabi-v7a-${{ matrix.build_type }}
          path: app-armeabi-v7a-${{ matrix.build_type }}.apk
#      - name: Upload x86_64 ${{ matrix.build_type }} APK
#        uses: actions/upload-artifact@v4
#        with:
#          name: apk-x86_64-${{ matrix.build_type }}
#          path: app-x86_64-${{ matrix.build_type }}.apk

  run_tooling_api_tests:
    name: Build and test Tooling API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run tooling API tests
        run: ./gradlew :tooling:impl:build --continue
        env:
          ANDROIDIDE_TEST: true
          TEST_TOOLING_API_IMPL: true
      - name: Upload test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-tooling-api-tests
          path: '**/build/reports/tests/'